name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: koyounggam
          password: cooki3s&cream

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: koyounggam/heomiverse-fe:latest
