name: Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git 체크아웃
        uses: actions/checkout@v4

      - name: pnpm 활성화
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Dockerhub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker 이미지 빌드 & 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: koyounggam/heomiverse-fe:latest

      - name: 서버 원격 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KIMZEOLMI_SSH_HOST }}
          username: ${{ secrets.KIMZEOLMI_SSH_USERNAME }}
          key: ${{ secrets.KIMZEOLMI_SSH_KEY }}
          script: |
            docker stop heomiverse-fe || true
            docker rm heomiverse-fe || true
            docker rmi koyounggam/heomiverse-fe:latest || true
            docker pull koyounggam/heomiverse-fe:latest
            docker run -d --name heomiverse-fe -p 80:80 --add-host=host.docker.internal:host-gateway koyounggam/heomiverse-fe:latest
            docker ps